main:
    - identifier: inicio
      name: Inicio
      url: /
      weight: 1
      params:
          newTab: false
          haveChildren: false
    - identifier: blog
      name: Blog
      url: /blog
      weight: 2
      params:
          newTab: false
          haveChildren: false
    - identifier: sobre
      name: Sobre
      url: /about
      weight: 3
      params:
          haveChildren: false
          children: false
    - identifier: contacto
      name: Contacto
      url: /contact
      weight: 4
      params:
          newTab: false
          haveChildren: false
    - identifier: apps
      name: Apps
      url: /apps
      weight: 5
      params:
          newTab: false
          haveChildren: false
    - identifier: roadmap
      name: Roadmap
      url: /roadmap
      weight: 6
      params:
          newTab: false
          haveChildren: false
